version: '3.8'

services:
  pedidos-api:
    build: ./pedidos_api
    ports:
      - "8000:8000"
    networks:
      - restaurante-net
    depends_on:
      - inventario-api

  inventario-api:
    build: ./inventario_api
    ports:
      - "8001:8001"
    networks:
      - restaurante-net

  jenkins:
    build: ./jenkins
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - inicio_jenkins:/var/jenkins_home
    networks:
      - restaurante-net

networks:
  restaurante-net:
    driver: bridge

volumes:
  inicio_jenkins:

