version: '3.8'

services:
  pedidos-api:
    build: ./pedidos_api
    ports:
      - "8000:8000"
    networks:
      - restaurant-net
    depends_on:
      - inventario-api

  inventario-api:
    build: ./inventario_api
    ports:
      - "8001:8001"
    networks:
      - restaurant-net

  jenkins:
    build: ./jenkins  # Esto tomará el Dockerfile desde la carpeta jenkins
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
    networks:
      - restaurant-net

networks:
  restaurant-net:
    driver: bridge
    
volumes:
  jenkins_home: